
baseURL = "https://example.com/"

[module]
[module.hugoVersion]
min = "0.56.0"
[[module.imports]]
path="github.com/lord/slate"
[[module.imports.mounts]]
source="source/images"
target="static/images"
[[module.imports.mounts]]
source="source/fonts"
target="static/fonts"
[[module.imports.mounts]]
source="source/stylesheets"
target="assets/scss/slate"
[[module.imports.mounts]]
source="source/javascripts"
target="assets/js/slate"

theme = "docuapi"
themesdir = "../.."
languageCode = "en-us"
baseurl = "https://docuapi.netlify.com/"
title = "DocuAPI Example Site"

disableKinds = ["taxonomyTerm"]

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
pygmentsUseClasses = false

defaultContentLanguage = "en"

[params]
search = true

# Configure the language example tabs.
[[params.language_tabs]]
key = "go"
name = "Go"
[[params.language_tabs]]
key = "shell"
name = "Shell"
[[params.language_tabs]]
key = "ruby"
name = "Ruby"
[[params.language_tabs]]
key = "python"
name = "Python"
[[params.language_tabs]]
key = "javascript"
name = "Javascript"

#Languages
[languages]

[languages.en]
languageName = "English"
weight = 2
title = "DocuAPI Example Site"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [
"<a href='#'>Sign Up for a Developer Key</a>",
"Documentation Powered by [DocuAPI](https://github.com/bep/docuapi)",
"Hugo Theme by [bep](https://github.com/bep)"
]
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true


[languages.nn]
languageName = "Nynorsk"
weight = 1
title = "DocuAPI-døme"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [
"<a href='#'>Registrer deg for ein utviklarnøkkel</a>",
"Dokumentasjonen er driven av [DocuAPI](https://github.com/bep/docuapi)",
"Hugo Theme av [bep](https://github.com/bep)"
]

[languages.nn.blackfriday]
# Norwegian uses angled quotes
angledQuotes = true
hrefTargetBlank = true
